/**
 * Learning Tools Interoperability Version 1.3 Final Release JSON Schema Binding (schema-deeplinkingrequest)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DeepLinkingSettingsType {
    /**
    * Model Primitive Datatype = String. This is a fully qualified URL where the Platform redirects the user back to the tool interface. This URL can be use once the Platform is finished.
    */
    'deepLinkReturnUrl': string;
    /**
    * Model Primitive Datatype = String. The set of types accepted.
    */
    'acceptTypes': Array<string>;
    /**
    * Model Primitive Datatype = String. The set of documents supported e.g. 'iframe', 'window', etc.
    */
    'acceptPresentationDocumentTargets': Array<string>;
    /**
    * Model Primitive Datatype = String. The set of media types (as defined in RFC 7321) the Platform accepts. This only applies to the file types.
    */
    'acceptMediaTypes'?: Array<string>;
    /**
    * Whether the Platform allows multiple content items to be submitted in a single response.
    */
    'acceptMultiple'?: DeepLinkingSettingsTypeAcceptMultipleEnum;
    /**
    * Whether any content items returned by the Tool would be automatically persisted without any option for the user to cancel the operation.
    */
    'autoCreate'?: DeepLinkingSettingsTypeAutoCreateEnum;
    /**
    * Model Primitive Datatype = String. Default text to be used as the title or alt text for the content item returned by the Tool. This value is normally short in length, for example, suitable for use as a heading.
    */
    'title'?: string;
    /**
    * Model Primitive Datatype = String. Default text to be used as the visible text for the content item returned by the Tool. If no text is returned by the Tool, the Platform may use the value of the 'title' parameter instead (if any). This value may be a long description of the content item.
    */
    'text'?: string;
    /**
    * Model Primitive Datatype = String. An opaque value which must be returned by the Tool in its response if it was passed in on the request.
    */
    'data'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "deepLinkReturnUrl",
            "baseName": "deep_link_return_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "acceptTypes",
            "baseName": "accept_types",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "acceptPresentationDocumentTargets",
            "baseName": "accept_presentation_document_targets",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "acceptMediaTypes",
            "baseName": "accept_media_types",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "acceptMultiple",
            "baseName": "accept_multiple",
            "type": "DeepLinkingSettingsTypeAcceptMultipleEnum",
            "format": ""
        },
        {
            "name": "autoCreate",
            "baseName": "auto_create",
            "type": "DeepLinkingSettingsTypeAutoCreateEnum",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeepLinkingSettingsType.attributeTypeMap;
    }

    public constructor() {
    }
}


export type DeepLinkingSettingsTypeAcceptMultipleEnum = "true" | "false" ;
export type DeepLinkingSettingsTypeAutoCreateEnum = "true" | "false" ;

