/**
 * Learning Tools Interoperability Version 1.3 Final Release JSON Schema Binding (schema-deeplinkingrequest)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The claims for the properties that describe aspects of how the sender expects to host the presentation of the message receiver's user experience.
*/
export class LaunchPresentationClaimType {
    /**
    * The kind of browser window or frame from which the user launched inside the message sender's system.
    */
    'documentTarget'?: LaunchPresentationClaimTypeDocumentTargetEnum;
    /**
    * Model Primitive Datatype = Integer. The height of the window or frame where the content from the message receiver will be displayed to the user.
    */
    'height'?: number;
    /**
    * Model Primitive Datatype = Integer. The width of the window or frame where the content from the message receiver will be displayed to the user.
    */
    'width'?: number;
    /**
    * Model Primitive Datatype = String. Fully qualified HTTPS URL within the message sender's user experience to where the message receiver can redirect the user back.
    */
    'returnUrl'?: string;
    /**
    * Model Primitive Datatype = String. Language, country and varuiant as represented using the IETF Best Practices for Tags for Identifying Languages.
    */
    'locale'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "documentTarget",
            "baseName": "document_target",
            "type": "LaunchPresentationClaimTypeDocumentTargetEnum",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": ""
        },
        {
            "name": "returnUrl",
            "baseName": "return_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LaunchPresentationClaimType.attributeTypeMap;
    }

    public constructor() {
    }
}


export type LaunchPresentationClaimTypeDocumentTargetEnum = "frame" | "iframe" | "window" ;

