/**
 * Learning Tools Interoperability Version 1.3 Final Release JSON Schema Binding (schema-deeplinkingrequest)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* This is the set of claims as defined by the IMS Security Framework.
*/
export class LTISecurityFrameworkJWTType {
    /**
    * Model Primitive Datatype = String. Issuer Identifier for the Issuer of the token. The iss value is a case sensitive URL using the https scheme that contains scheme, host, and optionally, port number and path components and no query or fragment components.
    */
    'iss': string;
    /**
    * Model Primitive Datatype = String. A locally unique and never reassigned identifier within the Issuer for the End-User, which is intended to be consumed by the Client, e.g., 24400320 or AItOawmwtWwcT0k51BayewNvutrJUqsvl6qs7A4. It MUST NOT exceed 255 ASCII characters in length. The sub value is a case sensitive string.
    */
    'sub'?: string;
    /**
    * Model Primitive Datatype = String. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the tool provider. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.
    */
    'aud': Array<string>;
    /**
    * Model Primitive Datatype = Integer. Expiration time on or after which the ID Token MUST NOT be accepted for processing. The processing of this parameter requires that the current date/time MUST be before the expiration date/time listed in the value. Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time. See RFC 3339 [RFC3339] for details regarding date/times in general and UTC in particular.
    */
    'exp': number;
    /**
    * Model Primitive Datatype = Integer. Time at which the JWT was issued. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time.
    */
    'iat': number;
    /**
    * Model Primitive Datatype = String. Authorized party - the party to which the ID Token was issued. If present, it MUST contain the OAuth 2.0 Client ID of this party.
    */
    'azp'?: string;
    /**
    * Model Primitive Datatype = String. String value used to associate a Client session with an ID Token, and to mitigate replay attacks.
    */
    'nonce': string;
    /**
    * This required attribute indicates the version of LTI to which the message conforms.
    */
    'httpsPurlImsglobalOrgSpecLtiClaimVersion': LTISecurityFrameworkJWTTypeHttpsPurlImsglobalOrgSpecLtiClaimVersionEnum;
    /**
    * Model Primitive Datatype = String. This required attribute contains a string that defines the platform-tool integration governing the message.
    */
    'httpsPurlImsglobalOrgSpecLtiClaimDeploymentId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "iss",
            "baseName": "iss",
            "type": "string",
            "format": ""
        },
        {
            "name": "sub",
            "baseName": "sub",
            "type": "string",
            "format": ""
        },
        {
            "name": "aud",
            "baseName": "aud",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "exp",
            "baseName": "exp",
            "type": "number",
            "format": ""
        },
        {
            "name": "iat",
            "baseName": "iat",
            "type": "number",
            "format": ""
        },
        {
            "name": "azp",
            "baseName": "azp",
            "type": "string",
            "format": ""
        },
        {
            "name": "nonce",
            "baseName": "nonce",
            "type": "string",
            "format": ""
        },
        {
            "name": "httpsPurlImsglobalOrgSpecLtiClaimVersion",
            "baseName": "https://purl.imsglobal.org/spec/lti/claim/version",
            "type": "LTISecurityFrameworkJWTTypeHttpsPurlImsglobalOrgSpecLtiClaimVersionEnum",
            "format": ""
        },
        {
            "name": "httpsPurlImsglobalOrgSpecLtiClaimDeploymentId",
            "baseName": "https://purl.imsglobal.org/spec/lti/claim/deployment_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LTISecurityFrameworkJWTType.attributeTypeMap;
    }

    public constructor() {
    }
}


export type LTISecurityFrameworkJWTTypeHttpsPurlImsglobalOrgSpecLtiClaimVersionEnum = "1.3.0" ;

