/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ContextClaimTypeTypeInner

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * This is the container for the set of claims for the context from within which the resource link occurs.
 *
 * @param id Model Primitive Datatype = String. Stable identifier that uniquely identifies the context from which the LTI message initiates. This MUST be locally unique to the 'deployment_id.
 * @param label Model Primitive Datatype = String. Short descriptive name for the context.
 * @param title Model Primitive Datatype = String. Full descriptive name for the context.
 * @param type An array of URI values for context types. The contained values come from either the associated enumerated vocabulary or a proprietary URI.
 */
@Serializable

data class ContextClaimType (

    /* Model Primitive Datatype = String. Stable identifier that uniquely identifies the context from which the LTI message initiates. This MUST be locally unique to the 'deployment_id. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* Model Primitive Datatype = String. Short descriptive name for the context. */
    @SerialName(value = "label") val label: kotlin.String? = null,

    /* Model Primitive Datatype = String. Full descriptive name for the context. */
    @SerialName(value = "title") val title: kotlin.String? = null,

    /* An array of URI values for context types. The contained values come from either the associated enumerated vocabulary or a proprietary URI. */
    @SerialName(value = "type") val type: kotlin.collections.List<ContextClaimTypeTypeInner>? = null

)

