/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param deepLinkReturnUrl Model Primitive Datatype = String. This is a fully qualified URL where the Platform redirects the user back to the tool interface. This URL can be use once the Platform is finished.
 * @param acceptTypes Model Primitive Datatype = String. The set of types accepted.
 * @param acceptPresentationDocumentTargets Model Primitive Datatype = String. The set of documents supported e.g. 'iframe', 'window', etc.
 * @param acceptMediaTypes Model Primitive Datatype = String. The set of media types (as defined in RFC 7321) the Platform accepts. This only applies to the file types.
 * @param acceptMultiple Whether the Platform allows multiple content items to be submitted in a single response.
 * @param autoCreate Whether any content items returned by the Tool would be automatically persisted without any option for the user to cancel the operation.
 * @param title Model Primitive Datatype = String. Default text to be used as the title or alt text for the content item returned by the Tool. This value is normally short in length, for example, suitable for use as a heading.
 * @param text Model Primitive Datatype = String. Default text to be used as the visible text for the content item returned by the Tool. If no text is returned by the Tool, the Platform may use the value of the 'title' parameter instead (if any). This value may be a long description of the content item.
 * @param `data` Model Primitive Datatype = String. An opaque value which must be returned by the Tool in its response if it was passed in on the request.
 */
@Serializable

data class DeepLinkingSettingsType (

    /* Model Primitive Datatype = String. This is a fully qualified URL where the Platform redirects the user back to the tool interface. This URL can be use once the Platform is finished. */
    @SerialName(value = "deep_link_return_url") @Required val deepLinkReturnUrl: kotlin.String,

    /* Model Primitive Datatype = String. The set of types accepted. */
    @SerialName(value = "accept_types") @Required val acceptTypes: kotlin.collections.List<kotlin.String>,

    /* Model Primitive Datatype = String. The set of documents supported e.g. 'iframe', 'window', etc. */
    @SerialName(value = "accept_presentation_document_targets") @Required val acceptPresentationDocumentTargets: kotlin.collections.List<kotlin.String>,

    /* Model Primitive Datatype = String. The set of media types (as defined in RFC 7321) the Platform accepts. This only applies to the file types. */
    @SerialName(value = "accept_media_types") val acceptMediaTypes: kotlin.collections.List<kotlin.String>? = null,

    /* Whether the Platform allows multiple content items to be submitted in a single response. */
    @SerialName(value = "accept_multiple") val acceptMultiple: DeepLinkingSettingsType.AcceptMultiple? = null,

    /* Whether any content items returned by the Tool would be automatically persisted without any option for the user to cancel the operation. */
    @SerialName(value = "auto_create") val autoCreate: DeepLinkingSettingsType.AutoCreate? = AutoCreate.`false`,

    /* Model Primitive Datatype = String. Default text to be used as the title or alt text for the content item returned by the Tool. This value is normally short in length, for example, suitable for use as a heading. */
    @SerialName(value = "title") val title: kotlin.String? = null,

    /* Model Primitive Datatype = String. Default text to be used as the visible text for the content item returned by the Tool. If no text is returned by the Tool, the Platform may use the value of the 'title' parameter instead (if any). This value may be a long description of the content item. */
    @SerialName(value = "text") val text: kotlin.String? = null,

    /* Model Primitive Datatype = String. An opaque value which must be returned by the Tool in its response if it was passed in on the request. */
    @SerialName(value = "data") val `data`: kotlin.String? = null

) {

    /**
     * Whether the Platform allows multiple content items to be submitted in a single response.
     *
     * Values: `true`,`false`
     */
    @Serializable
    enum class AcceptMultiple(val value: kotlin.String) {
        @SerialName(value = "true") `true`("true"),
        @SerialName(value = "false") `false`("false");
    }
    /**
     * Whether any content items returned by the Tool would be automatically persisted without any option for the user to cancel the operation.
     *
     * Values: `true`,`false`
     */
    @Serializable
    enum class AutoCreate(val value: kotlin.String) {
        @SerialName(value = "true") `true`("true"),
        @SerialName(value = "false") `false`("false");
    }
}

