/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The claims for the properties that describe aspects of how the sender expects to host the presentation of the message receiver's user experience.
 *
 * @param documentTarget The kind of browser window or frame from which the user launched inside the message sender's system.
 * @param height Model Primitive Datatype = Integer. The height of the window or frame where the content from the message receiver will be displayed to the user.
 * @param width Model Primitive Datatype = Integer. The width of the window or frame where the content from the message receiver will be displayed to the user.
 * @param returnUrl Model Primitive Datatype = String. Fully qualified HTTPS URL within the message sender's user experience to where the message receiver can redirect the user back.
 * @param locale Model Primitive Datatype = String. Language, country and varuiant as represented using the IETF Best Practices for Tags for Identifying Languages.
 */
@Serializable

data class LaunchPresentationClaimType (

    /* The kind of browser window or frame from which the user launched inside the message sender's system. */
    @SerialName(value = "document_target") val documentTarget: LaunchPresentationClaimType.DocumentTarget? = null,

    /* Model Primitive Datatype = Integer. The height of the window or frame where the content from the message receiver will be displayed to the user. */
    @SerialName(value = "height") val height: kotlin.Int? = null,

    /* Model Primitive Datatype = Integer. The width of the window or frame where the content from the message receiver will be displayed to the user. */
    @SerialName(value = "width") val width: kotlin.Int? = null,

    /* Model Primitive Datatype = String. Fully qualified HTTPS URL within the message sender's user experience to where the message receiver can redirect the user back. */
    @SerialName(value = "return_url") val returnUrl: kotlin.String? = null,

    /* Model Primitive Datatype = String. Language, country and varuiant as represented using the IETF Best Practices for Tags for Identifying Languages. */
    @SerialName(value = "locale") val locale: kotlin.String? = null

) {

    /**
     * The kind of browser window or frame from which the user launched inside the message sender's system.
     *
     * Values: frame,iframe,window
     */
    @Serializable
    enum class DocumentTarget(val value: kotlin.String) {
        @SerialName(value = "frame") frame("frame"),
        @SerialName(value = "iframe") iframe("iframe"),
        @SerialName(value = "window") window("window");
    }
}

