/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The set of claims for the properties associated with the platform initiating the launch.
 *
 * @param guid Model Primitive Datatype = String. A stable locally unique, to the 'iss' identifier, for an instance of the tool platform.
 * @param contactEmail Model Primitive Datatype = String. Administrative contact email for the platform instance.
 * @param description Model Primitive Datatype = String. A human readable description of the platform instance.
 * @param name Model Primitive Datatype = String. Name for the platform instance.
 * @param url Model Primitive Datatype = String. Home HTTPS URL endpoint for the platform instance.
 * @param productFamilyCode Model Primitive Datatype = String. Vendor product family code for the type of platform.
 * @param version Model Primitive Datatype = String. Vendor product version for the platform.
 */
@Serializable

data class ToolPlatformClaimType (

    /* Model Primitive Datatype = String. A stable locally unique, to the 'iss' identifier, for an instance of the tool platform. */
    @SerialName(value = "guid") @Required val guid: kotlin.String,

    /* Model Primitive Datatype = String. Administrative contact email for the platform instance. */
    @SerialName(value = "contact_email") val contactEmail: kotlin.String? = null,

    /* Model Primitive Datatype = String. A human readable description of the platform instance. */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* Model Primitive Datatype = String. Name for the platform instance. */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* Model Primitive Datatype = String. Home HTTPS URL endpoint for the platform instance. */
    @SerialName(value = "url") val url: kotlin.String? = null,

    /* Model Primitive Datatype = String. Vendor product family code for the type of platform. */
    @SerialName(value = "product_family_code") val productFamilyCode: kotlin.String? = null,

    /* Model Primitive Datatype = String. Vendor product version for the platform. */
    @SerialName(value = "version") val version: kotlin.String? = null

)

