# coding: utf-8

"""
    Learning Tools Interoperability Version 1.3 Final Release JSON Schema Binding (schema-deeplinkingrequest)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI


app = FastAPI(
    title="Learning Tools Interoperability Version 1.3 Final Release JSON Schema Binding (schema-deeplinkingrequest)",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="3.0",
)

