# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class LTISecurityFrameworkJWTType(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LTISecurityFrameworkJWTType - a model defined in OpenAPI

        iss: The iss of this LTISecurityFrameworkJWTType.
        sub: The sub of this LTISecurityFrameworkJWTType [Optional].
        aud: The aud of this LTISecurityFrameworkJWTType.
        exp: The exp of this LTISecurityFrameworkJWTType.
        iat: The iat of this LTISecurityFrameworkJWTType.
        azp: The azp of this LTISecurityFrameworkJWTType [Optional].
        nonce: The nonce of this LTISecurityFrameworkJWTType.
        https__purl_imsglobal_org_spec_lti_claim_version: The https__purl_imsglobal_org_spec_lti_claim_version of this LTISecurityFrameworkJWTType.
        https__purl_imsglobal_org_spec_lti_claim_deployment_id: The https__purl_imsglobal_org_spec_lti_claim_deployment_id of this LTISecurityFrameworkJWTType.
    """

    iss: str = Field(alias="iss")
    sub: Optional[str] = Field(alias="sub", default=None)
    aud: List[str] = Field(alias="aud")
    exp: int = Field(alias="exp")
    iat: int = Field(alias="iat")
    azp: Optional[str] = Field(alias="azp", default=None)
    nonce: str = Field(alias="nonce")
    https__purl_imsglobal_org_spec_lti_claim_version: str = Field(alias="https://purl.imsglobal.org/spec/lti/claim/version")
    https__purl_imsglobal_org_spec_lti_claim_deployment_id: str = Field(alias="https://purl.imsglobal.org/spec/lti/claim/deployment_id")

LTISecurityFrameworkJWTType.update_forward_refs()
