# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.context_claim_type import ContextClaimType
from openapi_server.models.launch_presentation_claim_type import LaunchPresentationClaimType
from openapi_server.models.tool_platform_claim_type import ToolPlatformClaimType


class LTIJWTMessageCoreTypeAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LTIJWTMessageCoreTypeAllOf - a model defined in OpenAPI

        name: The name of this LTIJWTMessageCoreTypeAllOf [Optional].
        given_name: The given_name of this LTIJWTMessageCoreTypeAllOf [Optional].
        family_name: The family_name of this LTIJWTMessageCoreTypeAllOf [Optional].
        middle_name: The middle_name of this LTIJWTMessageCoreTypeAllOf [Optional].
        picture: The picture of this LTIJWTMessageCoreTypeAllOf [Optional].
        email: The email of this LTIJWTMessageCoreTypeAllOf [Optional].
        locale: The locale of this LTIJWTMessageCoreTypeAllOf [Optional].
        https__purl_imsglobal_org_spec_lti_claim_roles: The https__purl_imsglobal_org_spec_lti_claim_roles of this LTIJWTMessageCoreTypeAllOf.
        https__purl_imsglobal_org_spec_lti_claim_role_scope_mentor: The https__purl_imsglobal_org_spec_lti_claim_role_scope_mentor of this LTIJWTMessageCoreTypeAllOf [Optional].
        https__purl_imsglobal_org_spec_lti_claim_context: The https__purl_imsglobal_org_spec_lti_claim_context of this LTIJWTMessageCoreTypeAllOf [Optional].
        https__purl_imsglobal_org_spec_lti_claim_tool_platform: The https__purl_imsglobal_org_spec_lti_claim_tool_platform of this LTIJWTMessageCoreTypeAllOf.
        https__purl_imsglobal_org_spec_lti_claim_launch_presentation: The https__purl_imsglobal_org_spec_lti_claim_launch_presentation of this LTIJWTMessageCoreTypeAllOf [Optional].
        https__purl_imsglobal_org_spec_lti_claim_custom: The https__purl_imsglobal_org_spec_lti_claim_custom of this LTIJWTMessageCoreTypeAllOf [Optional].
    """

    name: Optional[str] = Field(alias="name", default=None)
    given_name: Optional[str] = Field(alias="given_name", default=None)
    family_name: Optional[str] = Field(alias="family_name", default=None)
    middle_name: Optional[str] = Field(alias="middle_name", default=None)
    picture: Optional[str] = Field(alias="picture", default=None)
    email: Optional[str] = Field(alias="email", default=None)
    locale: Optional[str] = Field(alias="locale", default=None)
    https__purl_imsglobal_org_spec_lti_claim_roles: List[str] = Field(alias="https://purl.imsglobal.org/spec/lti/claim/roles")
    https__purl_imsglobal_org_spec_lti_claim_role_scope_mentor: Optional[List[str]] = Field(alias="https://purl.imsglobal.org/spec/lti/claim/role_scope_mentor", default=None)
    https__purl_imsglobal_org_spec_lti_claim_context: Optional[ContextClaimType] = Field(alias="https://purl.imsglobal.org/spec/lti/claim/context", default=None)
    https__purl_imsglobal_org_spec_lti_claim_tool_platform: ToolPlatformClaimType = Field(alias="https://purl.imsglobal.org/spec/lti/claim/tool_platform")
    https__purl_imsglobal_org_spec_lti_claim_launch_presentation: Optional[LaunchPresentationClaimType] = Field(alias="https://purl.imsglobal.org/spec/lti/claim/launch_presentation", default=None)
    https__purl_imsglobal_org_spec_lti_claim_custom: Optional[Dict[str, Any]] = Field(alias="https://purl.imsglobal.org/spec/lti/claim/custom", default=None)

LTIJWTMessageCoreTypeAllOf.update_forward_refs()
