# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.context_claim_type import ContextClaimType
from openapi_server.models.launch_presentation_claim_type import LaunchPresentationClaimType
from openapi_server.models.tool_platform_claim_type import ToolPlatformClaimType


class LTIJWTMessageCoreType(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LTIJWTMessageCoreType - a model defined in OpenAPI

        iss: The iss of this LTIJWTMessageCoreType.
        sub: The sub of this LTIJWTMessageCoreType [Optional].
        aud: The aud of this LTIJWTMessageCoreType.
        exp: The exp of this LTIJWTMessageCoreType.
        iat: The iat of this LTIJWTMessageCoreType.
        azp: The azp of this LTIJWTMessageCoreType [Optional].
        nonce: The nonce of this LTIJWTMessageCoreType.
        https__purl_imsglobal_org_spec_lti_claim_version: The https__purl_imsglobal_org_spec_lti_claim_version of this LTIJWTMessageCoreType.
        https__purl_imsglobal_org_spec_lti_claim_deployment_id: The https__purl_imsglobal_org_spec_lti_claim_deployment_id of this LTIJWTMessageCoreType.
        name: The name of this LTIJWTMessageCoreType [Optional].
        given_name: The given_name of this LTIJWTMessageCoreType [Optional].
        family_name: The family_name of this LTIJWTMessageCoreType [Optional].
        middle_name: The middle_name of this LTIJWTMessageCoreType [Optional].
        picture: The picture of this LTIJWTMessageCoreType [Optional].
        email: The email of this LTIJWTMessageCoreType [Optional].
        locale: The locale of this LTIJWTMessageCoreType [Optional].
        https__purl_imsglobal_org_spec_lti_claim_roles: The https__purl_imsglobal_org_spec_lti_claim_roles of this LTIJWTMessageCoreType.
        https__purl_imsglobal_org_spec_lti_claim_role_scope_mentor: The https__purl_imsglobal_org_spec_lti_claim_role_scope_mentor of this LTIJWTMessageCoreType [Optional].
        https__purl_imsglobal_org_spec_lti_claim_context: The https__purl_imsglobal_org_spec_lti_claim_context of this LTIJWTMessageCoreType [Optional].
        https__purl_imsglobal_org_spec_lti_claim_tool_platform: The https__purl_imsglobal_org_spec_lti_claim_tool_platform of this LTIJWTMessageCoreType.
        https__purl_imsglobal_org_spec_lti_claim_launch_presentation: The https__purl_imsglobal_org_spec_lti_claim_launch_presentation of this LTIJWTMessageCoreType [Optional].
        https__purl_imsglobal_org_spec_lti_claim_custom: The https__purl_imsglobal_org_spec_lti_claim_custom of this LTIJWTMessageCoreType [Optional].
    """

    iss: str = Field(alias="iss")
    sub: Optional[str] = Field(alias="sub", default=None)
    aud: List[str] = Field(alias="aud")
    exp: int = Field(alias="exp")
    iat: int = Field(alias="iat")
    azp: Optional[str] = Field(alias="azp", default=None)
    nonce: str = Field(alias="nonce")
    https__purl_imsglobal_org_spec_lti_claim_version: str = Field(alias="https://purl.imsglobal.org/spec/lti/claim/version")
    https__purl_imsglobal_org_spec_lti_claim_deployment_id: str = Field(alias="https://purl.imsglobal.org/spec/lti/claim/deployment_id")
    name: Optional[str] = Field(alias="name", default=None)
    given_name: Optional[str] = Field(alias="given_name", default=None)
    family_name: Optional[str] = Field(alias="family_name", default=None)
    middle_name: Optional[str] = Field(alias="middle_name", default=None)
    picture: Optional[str] = Field(alias="picture", default=None)
    email: Optional[str] = Field(alias="email", default=None)
    locale: Optional[str] = Field(alias="locale", default=None)
    https__purl_imsglobal_org_spec_lti_claim_roles: List[str] = Field(alias="https://purl.imsglobal.org/spec/lti/claim/roles")
    https__purl_imsglobal_org_spec_lti_claim_role_scope_mentor: Optional[List[str]] = Field(alias="https://purl.imsglobal.org/spec/lti/claim/role_scope_mentor", default=None)
    https__purl_imsglobal_org_spec_lti_claim_context: Optional[ContextClaimType] = Field(alias="https://purl.imsglobal.org/spec/lti/claim/context", default=None)
    https__purl_imsglobal_org_spec_lti_claim_tool_platform: ToolPlatformClaimType = Field(alias="https://purl.imsglobal.org/spec/lti/claim/tool_platform")
    https__purl_imsglobal_org_spec_lti_claim_launch_presentation: Optional[LaunchPresentationClaimType] = Field(alias="https://purl.imsglobal.org/spec/lti/claim/launch_presentation", default=None)
    https__purl_imsglobal_org_spec_lti_claim_custom: Optional[Dict[str, Any]] = Field(alias="https://purl.imsglobal.org/spec/lti/claim/custom", default=None)

LTIJWTMessageCoreType.update_forward_refs()
