# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ToolPlatformClaimType(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ToolPlatformClaimType - a model defined in OpenAPI

        guid: The guid of this ToolPlatformClaimType.
        contact_email: The contact_email of this ToolPlatformClaimType [Optional].
        description: The description of this ToolPlatformClaimType [Optional].
        name: The name of this ToolPlatformClaimType [Optional].
        url: The url of this ToolPlatformClaimType [Optional].
        product_family_code: The product_family_code of this ToolPlatformClaimType [Optional].
        version: The version of this ToolPlatformClaimType [Optional].
    """

    guid: str = Field(alias="guid")
    contact_email: Optional[str] = Field(alias="contact_email", default=None)
    description: Optional[str] = Field(alias="description", default=None)
    name: Optional[str] = Field(alias="name", default=None)
    url: Optional[str] = Field(alias="url", default=None)
    product_family_code: Optional[str] = Field(alias="product_family_code", default=None)
    version: Optional[str] = Field(alias="version", default=None)

ToolPlatformClaimType.update_forward_refs()
